<?php

declare(strict_types=1);

namespace Psimandl\TrainerWorkflowBundle\EventListener\DataContainer;

use Contao\DataContainer;
use Contao\Input;
use Contao\StringUtil;
use Psimandl\TrainerWorkflowBundle\Model\RuleModel;
use Psimandl\TrainerWorkflowBundle\Model\WorkflowModel;

/**
 * Presentational, option and validation callbacks for the answer-field
 * (tl_trainer_question) and PDF-rule (tl_trainer_rule) child tables.
 *
 * Must stay free of constructor dependencies: the MultiColumnWizard and the
 * dcaWizard callbacks resolve this class via System::importStatic(), which
 * instantiates it without container injection.
 */
class AnswerConfigListener
{
    /**
     * Renders one answer-field row in the workflow's child view.
     *
     * @param array<string, mixed> $row
     */
    public function renderQuestionRecord(array $row): string
    {
        $label = StringUtil::specialchars((string) ($row['label'] ?? ''));
        $type = (string) ($row['type'] ?? '');
        $typeLabel = $GLOBALS['TL_LANG']['tl_trainer_question']['typeOptions'][$type] ?? $type;
        $storage = StringUtil::specialchars((string) ($row['storageField'] ?? ''));

        return sprintf(
            '<div class="tl_content_left"><strong>%s</strong> <span style="color:#999">[%s &rarr; %s]</span></div>',
            $label,
            StringUtil::specialchars((string) $typeLabel),
            $storage,
        );
    }

    /**
     * Renders the embedded PDF-rule list (dcaWizard list_callback): label +
     * readable conditions ("(Standardtext)" for a rule without conditions),
     * plus the edit/delete operations generated by the wizard itself.
     *
     * @param array<int, array<string, mixed>> $records
     */
    public function renderRulesList(array $records, string $id, object $widget): string
    {
        if ([] === $records) {
            return '<p>'.StringUtil::specialchars((string) ($GLOBALS['TL_LANG']['tl_trainer_workflow']['rulesEmpty'] ?? '')).'</p>';
        }

        $hLabel = $GLOBALS['TL_LANG']['tl_trainer_rule']['title'][0] ?? 'Bezeichnung';
        $hCond = $GLOBALS['TL_LANG']['tl_trainer_rule']['conditions'][0] ?? 'Bedingung';

        $body = '';
        $defaultCount = 0;

        foreach ($records as $row) {
            $title = trim((string) ($row['title'] ?? ''));

            if ('' === $title) {
                $title = ($GLOBALS['TL_LANG']['tl_trainer_rule']['untitled'] ?? 'Rule').' '.(int) ($row['id'] ?? 0);
            }

            $isDefault = '1' === (string) ($row['isDefault'] ?? '');

            if ($isDefault) {
                ++$defaultCount;
                $conditionText = '<em>('.StringUtil::specialchars((string) ($GLOBALS['TL_LANG']['tl_trainer_rule']['alwaysLabel'] ?? 'Standardtext')).')</em>';
            } else {
                $conditionText = $this->formatConditions($row['conditions'] ?? null) ?: '–';
            }

            $operations = $widget->generateRowOperation('edit', $row).$widget->generateRowOperation('delete', $row);

            $body .= '<tr class="hover-row">'
                .'<td class="tl_file_list">'.StringUtil::specialchars($title).'</td>'
                .'<td class="tl_file_list">'.$conditionText.'</td>'
                .'<td class="tl_file_list tl_right_nowrap">'.$operations.'</td>'
                .'</tr>';
        }

        // There should be exactly one rule without conditions (the "Standardtext").
        $warning = '';

        if ($defaultCount > 1) {
            $warning = '<p class="tl_error">'.StringUtil::specialchars((string) ($GLOBALS['TL_LANG']['tl_trainer_rule']['defaultRuleError'] ?? '')).'</p>';
        } elseif (0 === $defaultCount) {
            $warning = '<p class="tl_info">'.StringUtil::specialchars((string) ($GLOBALS['TL_LANG']['tl_trainer_rule']['defaultMissing'] ?? '')).'</p>';
        }

        return $warning.'<table class="tl_listing showColumns"><thead><tr>'
            .'<th class="tl_folder_tlist">'.StringUtil::specialchars((string) $hLabel).'</th>'
            .'<th class="tl_folder_tlist">'.StringUtil::specialchars((string) $hCond).'</th>'
            .'<th class="tl_folder_tlist"></th>'
            .'</tr></thead><tbody>'.$body.'</tbody></table>';
    }

    /**
     * Human-readable summary of a rule's conditions; empty string when none.
     *
     * @param mixed $value serialized conditions
     */
    private function formatConditions(mixed $value): string
    {
        $conditions = $this->extractConditions($value);

        if ([] === $conditions) {
            return '';
        }

        $operators = $GLOBALS['TL_LANG']['tl_trainer_rule']['operatorOptions'] ?? [];
        $parts = [];

        foreach ($conditions as $condition) {
            $operatorLabel = (string) ($operators[$condition['operator']] ?? $condition['operator']);
            $value = \in_array($condition['operator'], ['empty', 'notempty'], true) ? '' : ' '.$condition['value'];
            $parts[] = trim($condition['field'].' '.$operatorLabel.$value);
        }

        $and = ' '.($GLOBALS['TL_LANG']['tl_trainer_rule']['condAnd'] ?? 'und').' ';

        return StringUtil::specialchars(implode($and, $parts));
    }

    /**
     * onload_callback for tl_trainer_rule: when the rule is the "Standardtext"
     * (isDefault), remove the conditions field from the edit palette so it is
     * hidden and not validated. Toggling the checkbox (submitOnChange) reloads
     * the form, re-running this callback.
     */
    public function hideConditionsForDefaultRule(DataContainer $dc): void
    {
        if (!$dc->id) {
            return;
        }

        $rule = RuleModel::findByPk((int) $dc->id);

        if (null === $rule || !$rule->isDefaultRule()) {
            return;
        }

        $palette = &$GLOBALS['TL_DCA']['tl_trainer_rule']['palettes']['default'];
        $palette = str_replace(',conditions', '', (string) $palette);
    }

    /**
     * Complete conditions (rows with field + operator) of a serialized value.
     *
     * @param mixed $value
     *
     * @return array<int, array{field: string, operator: string, value: string}>
     */
    private function extractConditions(mixed $value): array
    {
        $conditions = [];

        foreach (StringUtil::deserialize($value, true) as $row) {
            $field = trim((string) ($row['field'] ?? ''));
            $operator = trim((string) ($row['operator'] ?? ''));

            if ('' !== $field && '' !== $operator) {
                $conditions[] = ['field' => $field, 'operator' => $operator, 'value' => (string) ($row['value'] ?? '')];
            }
        }

        return $conditions;
    }

    /**
     * Options for a rule condition's "field" column: the storage fields
     * configured on the rule's parent workflow.
     *
     * @return array<string, string>
     */
    public function getStorageFieldOptions(): array
    {
        $workflow = WorkflowModel::findByPk($this->resolveRuleWorkflowId());

        if (null === $workflow) {
            return [];
        }

        $fields = $workflow->getStorageFields();

        return [] === $fields ? [] : array_combine($fields, $fields);
    }

    /**
     * Resolves the parent workflow id of the rule currently being edited or
     * created. On edit "id" is the rule; on create "pid" is either the parent
     * workflow (PASTE_INTO) or a sibling rule (PASTE_AFTER, mode 1).
     */
    private function resolveRuleWorkflowId(): int
    {
        $ruleId = (int) Input::get('id');

        if ($ruleId > 0 && 'create' !== Input::get('act')) {
            $rule = RuleModel::findByPk($ruleId);

            if (null !== $rule) {
                return (int) $rule->pid;
            }
        }

        $pid = (int) Input::get('pid');

        if ($pid < 1) {
            return 0;
        }

        if (1 === (int) Input::get('mode')) {
            $sibling = RuleModel::findByPk($pid);

            return null !== $sibling ? (int) $sibling->pid : 0;
        }

        return $pid;
    }
}
