<?php

declare(strict_types=1);

namespace Psimandl\WorkflowBundle\Tests\Excel;

use PhpOffice\PhpSpreadsheet\Cell\Cell;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PHPUnit\Framework\TestCase;
use Psimandl\WorkflowBundle\Excel\CellReader;
use Psimandl\WorkflowBundle\Excel\FormatCodeParser;
use Psimandl\WorkflowBundle\Excel\ValueFormatter;

/**
 * The CellReader is the only door from a spreadsheet cell into this bundle, so its contract
 * is what every stored value depends on.
 *
 * The formula rule is deliberate: a formula is NEVER evaluated. Only the result the
 * spreadsheet program itself wrote into the file counts. Recalculating would require
 * PhpSpreadsheet's engine to understand every function of a foreign file – where it does not,
 * the import would either abort with a CalculationException or store a number the file never
 * showed. Without a usable result the cell reads as empty and the importer reports the row.
 */
final class CellReaderTest extends TestCase
{
    private CellReader $reader;
    private Spreadsheet $spreadsheet;

    protected function setUp(): void
    {
        $this->reader = new CellReader(new FormatCodeParser(), new ValueFormatter());
        $this->spreadsheet = new Spreadsheet();
    }

    /**
     * @param mixed $cached the result stored in the file; null = none (as in a file written
     *                      by a tool without a calculation engine)
     */
    private function formulaCell(string $formula, mixed $cached, string $mask = 'General'): Cell
    {
        $sheet = $this->spreadsheet->getActiveSheet();
        $sheet->setCellValue('A1', $formula);
        $cell = $sheet->getCell('A1');

        if (null !== $cached) {
            $cell->setCalculatedValue($cached);
        }

        $sheet->getStyle('A1')->getNumberFormat()->setFormatCode($mask);

        self::assertTrue($cell->isFormula(), 'test fixture must be a formula cell');

        return $cell;
    }

    private function literalCell(mixed $value, string $mask = 'General'): Cell
    {
        $sheet = $this->spreadsheet->getActiveSheet();
        $sheet->setCellValue('B1', $value);
        $sheet->getStyle('B1')->getNumberFormat()->setFormatCode($mask);

        return $sheet->getCell('B1');
    }

    /**
     * The whole point of the change: a currency formula must read exactly like a literal
     * currency cell ("3.000,00 €"), not like PhpSpreadsheet's US rendering of the mask.
     */
    public function testFormulaWithStoredCurrencyResultIsLocalised(): void
    {
        $cell = $this->formulaCell('=B2*C2', 3000, '#,##0.00\ [$€-407]');

        self::assertSame('3.000,00 €', $this->reader->read($cell));
        self::assertNull($this->reader->formulaProblem($cell));
    }

    public function testFormulaWithStoredDateResultBecomesGermanDate(): void
    {
        // 20440 = 1955-12-17 as an Excel serial.
        $cell = $this->formulaCell('=EDATE(D2,0)', 20440, 'm/d/yyyy');

        self::assertSame('17.12.1955', $this->reader->read($cell));
    }

    public function testFormulaWithStoredTextResultIsKept(): void
    {
        $cell = $this->formulaCell('=CONCATENATE(A2," ",B2)', 'Max Mustermann');

        self::assertSame('Max Mustermann', $this->reader->read($cell));
        self::assertNull($this->reader->formulaProblem($cell));
    }

    /**
     * No stored result (e.g. a file generated by a tool without a calculation engine): empty
     * field plus a reportable reason – never a guess.
     */
    public function testFormulaWithoutStoredResultReadsEmptyAndIsReported(): void
    {
        $cell = $this->formulaCell('=SUM(B2:B9)', null, '#,##0.00');

        self::assertSame('', $this->reader->read($cell));
        self::assertSame('kein gespeichertes Ergebnis', $this->reader->formulaProblem($cell));
    }

    /**
     * An error literal is a value in the file but not data: "#NV" must not travel into the
     * form, the document and the export.
     *
     * @dataProvider errorValues
     */
    public function testStoredErrorValueCountsAsNoResult(string $error): void
    {
        $cell = $this->formulaCell('=VLOOKUP(A2,X:Y,2,FALSE)', $error);

        self::assertSame('', $this->reader->read($cell));
        self::assertSame(sprintf('Fehlerwert „%s"', $error), $this->reader->formulaProblem($cell));
    }

    /**
     * @return array<string, array<int, string>>
     */
    public static function errorValues(): array
    {
        return [
            'German #NV'      => ['#NV'],
            'English #N/A'    => ['#N/A'],
            'division by nil' => ['#DIV/0!'],
            'German #BEZUG!'  => ['#BEZUG!'],
        ];
    }

    /**
     * A function PhpSpreadsheet's engine does not know must not reach the engine at all: with
     * a stored result the cell reads fine, without one it reads empty – in neither case does
     * anything throw.
     */
    public function testUnsupportedFunctionIsNeverEvaluated(): void
    {
        $withResult = $this->formulaCell('=SOMEADDIN.FUNCTION(A2)', 42, '#,##0.00');
        self::assertSame('42,00', $this->reader->read($withResult));

        $this->spreadsheet = new Spreadsheet();
        $withoutResult = $this->formulaCell('=SOMEADDIN.FUNCTION(A2)', null);
        self::assertSame('', $this->reader->read($withoutResult));
    }

    /**
     * rawValue() is what the column analysis judges a column by: the stored result, so a
     * formula column counts as numeric instead of "text instead of a number".
     */
    public function testRawValueYieldsTheStoredResult(): void
    {
        self::assertSame(3000, $this->reader->rawValue($this->formulaCell('=B2*C2', 3000)));

        $this->spreadsheet = new Spreadsheet();
        self::assertNull($this->reader->rawValue($this->formulaCell('=B2*C2', null)));
    }

    /**
     * A percent format is one of the kinds this bundle does not re-render; the formula path
     * must fall back to the mask instead of to getFormattedValue() (which would evaluate).
     */
    public function testUntouchedKindKeepsTheMaskRendering(): void
    {
        $cell = $this->formulaCell('=B2/C2', 0.25, '0%');

        self::assertSame('25%', $this->reader->read($cell));
    }

    /**
     * Regression guard for the literal path – it is untouched by the formula handling.
     */
    public function testLiteralCellsAreUnaffected(): void
    {
        self::assertSame('3.000,00 €', $this->reader->read($this->literalCell(3000, '#,##0.00\ [$€-407]')));
        self::assertSame('17.12.1955', $this->reader->read($this->literalCell(20440, 'm/d/yyyy')));
        self::assertSame('Beispiel', $this->reader->read($this->literalCell('Beispiel')));
        self::assertNull($this->reader->formulaProblem($this->literalCell('Beispiel')));
    }
}
